### ISSUE TITLE
Broken Pipe on Bungeecord plugin

### ISSUE THREAD

**Issue by G-Lauz** [G-Lauz/PlayerJoinGroup#10]
The error occur several time after the Spigots servers have been reboot and not immediately after the event.
<details><summary>Broken Pipe Error</summary>
<p>

14:29:51 [WARNING] Error dispatching event PlayerDisconnectEvent(player=viclarque) to listener fr.freebuild.playerjoingroup.bungee.listener.PlayerDisconnectListener@504243a2
java.lang.RuntimeException: java.net.SocketException: Broken pipe
        &emsp;at fr.freebuild.playerjoingroup.bungee.MessagesManager.lambda$sendToAll$0(MessagesManager.java:164)
        &emsp;at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        &emsp;at fr.freebuild.playerjoingroup.bungee.MessagesManager.lambda$sendToAll$1(MessagesManager.java:160)
        &emsp;at java.base/java.util.Hashtable.forEach(Hashtable.java:895)
        &emsp;at fr.freebuild.playerjoingroup.bungee.MessagesManager.sendToAll(MessagesManager.java:158)
        &emsp;at fr.freebuild.playerjoingroup.bungee.listener.ConnectionListener.broadcastEvent(ConnectionListener.java:50)
        &emsp;at fr.freebuild.playerjoingroup.bungee.listener.PlayerDisconnectListener.on(PlayerDisconnectListener.java:20)
        &emsp;at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        &emsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        &emsp;at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        &emsp;at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
        &emsp;at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
        &emsp;at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:413)
        &emsp;at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:68)
        &emsp;at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:60)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
        &emsp;at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
        &emsp;at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
        &emsp;at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
        &emsp;at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
        &emsp;at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
        &emsp;at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
        &emsp;at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        &emsp;at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
        &emsp;at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        &emsp;at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        &emsp;at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        &emsp;at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
        &emsp;at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        &emsp;at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        &emsp;at java.base/java.lang.Thread.run(Thread.java:833)

</p>
</details>

**Comment by G-Lauz** [comment]
The error occur when a player is connected to the Spigot server while it's being close. The previous commit should handle the error.

If possible, the Spigot server should detect when it's about to go down and close the connection properly.
